M48
; DRILL file {KiCad 7.0.5-4d25ed1034~172~ubuntu22.04.1} date Do 26 Okt 2023 19:17:18
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-26T19:17:18+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-4d25ed1034~172~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X107.8Y-87.0
X126.1Y-73.9
T0
M30
