M48
; DRILL file {KiCad 7.0.5-4d25ed1034~172~ubuntu22.04.1} date Sa 17 Jun 2023 20:58:03
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-06-17T20:58:03+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-4d25ed1034~172~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X107.8Y-87.0
X126.1Y-73.9
T0
M30
